# Pandas

In [1]:
import pandas as pd

In [7]:
df = pd.read_csv(r"C:\Users\omkar\OneDrive\Desktop\Data Analyst\Python\Demo\csv files\Sales.csv")

In [16]:
pd.set_option('display.max.rows', 8)
pd.set_option('display.max.columns', 8)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row Labels      6 non-null      str
 1   Sum of Profit   6 non-null      float64
 2   Sum of Cost     6 non-null      float64
 3   Sum of Revenue  6 non-null      str
dtypes: float64(2), str(2)
memory usage: 356.0 bytes

In [18]:
df.shape

(7, 4)

In [19]:
df.head(5)

        Row Labels  Sum of Profit  Sum of Cost Sum of Revenue
0  New South Wales      3133684.0    6069811.0         43.20%
1       Queensland      3133684.0    6069811.0         23.78%
2  South Australia      3133684.0    6069811.0          6.56%
3         Tasmania      3133684.0    6069811.0          2.72%
4         Victoria      3133684.0    6069811.0         23.73%

In [20]:
df.tail(4)

    Row Labels  Sum of Profit  Sum of Cost Sum of Revenue
3     Tasmania      3133684.0    6069811.0          2.72%
4     Victoria      3133684.0    6069811.0         23.73%
5  Grand Total      3133684.0    6069811.0        100.00%
6          NaN            NaN          NaN            NaN

In [21]:
df['Row Labels']

0    New South Wales
1         Queensland
2    South Australia
3           Tasmania
4           Victoria
5        Grand Total
6                NaN
Name: Row Labels, dtype: str

In [32]:
# For All types of values
df.loc[5]

Row Labels        Grand Total
Sum of Profit       3133684.0
Sum of Cost         6069811.0
Sum of Revenue        100.00%
Name: 5, dtype: object

In [34]:
# For int values only 
df.iloc[4]

Row Labels         Victoria
Sum of Profit     3133684.0
Sum of Cost       6069811.0
Sum of Revenue       23.73%
Name: 4, dtype: object